// flow-typed signature: 21994dc801a7aaebd90fe28eb2c2e8c9
// flow-typed version: <<STUB>>/glamor-reset_v^3.0.0-1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'glamor-reset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'glamor-reset' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'glamor-reset/es6/index' {
  declare module.exports: any;
}

declare module 'glamor-reset/lib/index' {
  declare module.exports: any;
}

declare module 'glamor-reset/src/index' {
  declare module.exports: any;
}

declare module 'glamor-reset/umd/index' {
  declare module.exports: any;
}

declare module 'glamor-reset/umd/index.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'glamor-reset/es6/index.js' {
  declare module.exports: $Exports<'glamor-reset/es6/index'>;
}
declare module 'glamor-reset/lib/index.js' {
  declare module.exports: $Exports<'glamor-reset/lib/index'>;
}
declare module 'glamor-reset/src/index.js' {
  declare module.exports: $Exports<'glamor-reset/src/index'>;
}
declare module 'glamor-reset/umd/index.js' {
  declare module.exports: $Exports<'glamor-reset/umd/index'>;
}
declare module 'glamor-reset/umd/index.min.js' {
  declare module.exports: $Exports<'glamor-reset/umd/index.min'>;
}
